apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-2
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80

  - name: c2
    image: praveenseeme/login-2424
    ports:
    - containerPort: 8080